version: '3.9'
services:
  backend:
    container_name: ted_backend
    image: tegfleettrackeracr.azurecr.io/tedapi:0.0.1
    ports:
      - '3000:3000'
    env_file:
      - .env
  frontend:
    container_name: ted_frontend
    image: tegfleettrackeracr.azurecr.io/tedfrontend:0.0.1
    env_file:
      - .env
    ports:
      - '4200:4200'
